# kubernetes deployment called rucio-client using aaarora/rucio-client image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-client
  labels:
    app: rucio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-client
  template:
    metadata:
      labels:
        app: rucio-client
    spec:
      containers:
      - name: rucio-client
        env:
        - name: RUCIO_ACCOUNT
          value: "root"
        - name: X509_USER_PROXY
          value: "/home/x509"
        image: aaarora/rucio-client
        command: ["sh", "-c"]
        volumeMounts:
        - name: rucio-server-rucio-x509up
          mountPath: /home/x509
          subPath: x509up
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        args: ["while true; do sleep 30; done"]
      nodeSelector:
        nautilus.io/ipv6: "true"
      volumes:
      - name: rucio-server-rucio-x509up
        secret:
          secretName: rucio-server-rucio-x509up